title: Brighter Eyes Lynxes
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_style: grid
palette: grey
header:
  title: Brighter Eyes Lynxes
  logo_img: images/logo2.svg
  logo_img_alt: Brighter Eyes Lynxes
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: About
      url: /about
      style: link
footer:
  content: >-
    &copy; Brighter Eyes Lynxes. 
  has_social: true
  social_links:
    - label: GitHub
      url: 'https://github.com/brightereyeslynxes'
      style: icon
      icon_class: github
      new_window: true
  has_subscribe: False
  subscribe_title: Subscribe for new updates
  subscribe_content: >-
  subscribe_action: /subscribe-success
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
